/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as statemachine from "./statemachine";
export type { statemachine };
export type { Generic } from "./Generic";
